config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards
    resources :categories
    resources :receipts
    get "/receipts/index/:scope", to: "receipts#scoped", as: "scope"
    resources :suppliers
  end

  devise_for :users
  
  get "/welcome/chart_per_category", to: "welcome#chart_per_category"

  get 'welcome/index'
 
  root 'welcome#index'

  resources :receipts
end

app/models/receipt.rb
# frozen_string_literal: true

# Main receipt class which groups all data related to one physical/mail receipt
class Receipt < ApplicationRecord
  belongs_to :project, default: -> { Current.project }
  belongs_to :supplier, optional: true
  belongs_to :category, optional: true

  has_many :lines

  accepts_nested_attributes_for :lines,
                                allow_destroy: true,
                                reject_if: lambda { |attributes|
                                  attributes['description'].blank?
                                }

  monetize :value_cents

  has_many_attached :images

  enum status: {
    waiting: 0,
    processed: 1
  }
end

app/controllers/admin/receipts_controller.rb
# frozen_string_literal: true

module Admin
  # Handles the processing of receipts internally
  class ReceiptsController < AdminController
    def index
      @receipts = Receipt.order('created_at ASC').waiting.with_attached_images
    end

    def scoped
      @receipts = Receipt.order('created_at ASC').where(status: params[:scope]).with_attached_images
      render 'index'
    end

    def edit
      @receipt = Receipt.find(params[:id])
      20.times { @receipt.lines.build }
    end

    def update
      @receipt = Receipt.find(params[:id])

      receipt_params_modified = receipt_params

      # receipt_params_modified[:status] = :processed

      if @receipt.update(receipt_params_modified)
        redirect_to admin_receipts_path
      else
        render 'edit'
      end
    end

    private

    def receipt_params
      params.require(:receipt).permit(:value,
                                      :supplier_id,
                                      :category_id,
                                      :status,
                                      images: [],
                                      lines_attributes: %i[
                                        id
                                        amount
                                        description
                                        price
                                        price_total
                                      ])
    end
  end
end

app/controllers/receipts_controller.rb
# frozen_string_literal: true

# Handles creation of new receipts and viewing them
class ReceiptsController < ApplicationController
  before_action :authenticate_user!

  def index
    @receipts = Current.project.receipts.order('created_at DESC').processed.with_attached_images.includes(:supplier)
  end

  def new; end

  def show
    # render plain: current_user.inspect
    @receipt = Current.project.receipts.find(params[:id])
  end

  def create
    # Send before saving so we know someone is trying to send something 
    AdminMailer.receipt_email.deliver_now

    @receipt = Current.project.receipts.new(receipt_params)

    @receipt.save!
    redirect_to root_path
  end

  private

  def receipt_params
    params.require(:receipt).permit(:q, :value, images: [])
  end
end

app/views/admin/receipts/edit.html.erb
<%= form_with(model: [:admin, @receipt], local: true) do |form| %>
  <div class="row">
    <div class="col">
      <% @receipt.images.each do |image| %>
        <%= image_tag image.variant(resize: "500x800") %>
      <% end %>
    </div>

    <div class="col">


      <% if @receipt.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@receipt.errors.count, "error") %> prohibited
            this receipt from being saved:
          </h2>
          <ul>
            <% @receipt.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div data-controller="receipts--lines" id="lines-controller">
        <%= form.label :value %> Enter total amount:
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text"><%= currency_symbol %></span>
          </div>
          <%= form.text_field :value, { class: 'form-control', data: { target: 'receipts--lines.total', action: 'change->receipts--lines#hideOrShowContainerWhenNeeded' } } %>
        </div>

        <p>
          <%= form.label :supplier_id %><br>
          <%= form.collection_select(:supplier_id, Supplier.all, :id, :name, :prompt => 'Select' ) %>
          <%= link_to 'Leverancier toevoegen', new_admin_supplier_path %>
        </p>

        <p>
          <%= form.label :category_id %><br>
          <%= form.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Select' ) %>
          <%= link_to 'Categorie toevoegen', new_admin_category_path %>
        </p>

        <p>
          <%= form.label :status %><br>
          <%= form.select(:status, Receipt.statuses.keys.map {|status| [status.titleize,status]}, { selected: :processed }) %>
        </p>

        

        <div data-controller="receipt--lines" data-target="receipts--lines.container">
          <%= form.fields_for :lines do |l| %>
            <p data-controller="receipts--line">
              <%= l.number_field :amount, { class: 'receipts--line-amount', data: { target: 'receipts--line.amount receipts--lines.amount', action: 'change->receipts--lines#calculateTotal change->receipts--line#calculate ' } } %>x
              <%= l.text_field :description %>
              <%= l.text_field :price, { class: 'receipts--line-price',  data: { target: 'receipts--line.price receipts--lines.price', action: 'change->receipts--lines#calculateTotal change->receipts--line#calculate ' } } %>
              <%= l.text_field :price_total, { class: 'receipts--line-priceTotal',  readonly: true, data: { target: 'receipts--line.priceTotal receipts--lines.priceTotal'} } %>
            </p>
          <% end %>

          <p data-controller="receipt--lines" data-target="receipts--lines.submitContainer">
            <%= form.submit %>
          </p>
          

        </div>
      </div>
     
    </div>
  </div>

 <% end %>

app/views/admin/receipts/index.html.erb
<h1>Te verwerken</h1>

<%= link_to 'Waiting', admin_scope_path(:waiting) %>
<%= link_to 'Processed', admin_scope_path(:processed) %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @receipts.each do |receipt| %>
    <tr class="receipt-<%= receipt.id %>">
      <td><%= receipt.id %></td>
      <td><%= receipt.status %></td>
      <td><%= humanized_money_with_symbol receipt.value %></td>

      <% receipt.images.each do |image| %>
        <td><%= image_tag image.variant(resize: "200x200") %></td>
      <% end %>

      <td><%= link_to 'Verwerken', edit_admin_receipt_path(receipt) %></td>
    </tr>
  <% end %>
</table>