config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards
    resources :categories
    resources :receipts
    get "/receipts/index/:scope", to: "receipts#scoped", as: "scope"
    resources :suppliers
  end

  devise_for :users
  
  get "/welcome/chart_per_category", to: "welcome#chart_per_category"

  get 'welcome/index'
 
  root 'welcome#index'

  resources :receipts
end

app/models/supplier.rb
# frozen_string_literal: true

# The company which sent the receipt
class Supplier < ApplicationRecord
  has_many :receipt
end

app/controllers/admin/suppliers_controller.rb
# frozen_string_literal: true

module Admin
  # Basic management for suppliers
  class SuppliersController < AdminController
    before_action :set_supplier, only: %i[show edit update destroy]

    def index
      @suppliers = Supplier.all
    end

    def show; end

    def new
      @supplier = Supplier.new
    end

    def edit; end

    def create
      @supplier = Supplier.new(supplier_params)

      respond_to do |format|
        if @supplier.save
          format.html { redirect_to [:admin, @supplier], notice: 'Supplier was successfully created.' }
          format.json { render :show, status: :created, location: @supplier }
        else
          format.html { render :new }
          format.json { render json: @supplier.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @supplier.update(supplier_params)
          format.html { redirect_to [:admin, @supplier], notice: 'Supplier was successfully updated.' }
          format.json { render :show, status: :ok, location: @supplier }
        else
          format.html { render :edit }
          format.json { render json: @supplier.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @supplier.destroy
      respond_to do |format|
        format.html { redirect_to uppliers_url, notice: 'Supplier was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name)
    end
  end
end

app/views/admin/suppliers/_form.html.erb
<%= form_with(model: [:admin, @supplier], local: true) do |form| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/suppliers/edit.html.erb
<h1>Editing Admin Supplier</h1>

<%= render 'form', admin_supplier: @admin_supplier %>

<%= link_to 'Show', @admin_supplier %> |
<%= link_to 'Back', admin_suppliers_path %>

app/views/admin/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= link_to 'Show', admin_supplier_path(supplier) %></td>
        <td><%= link_to 'Edit', edit_admin_supplier_path(supplier) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Supplier', new_admin_supplier_path %>

app/views/admin/suppliers/new.html.erb
<h1>New Admin Supplier</h1>

<%= render 'form', admin_supplier: @supplier %>

<%= link_to 'Back', admin_suppliers_path %>

app/views/admin/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<%= link_to 'Edit', edit_admin_supplier_path(@supplier) %> |
<%= link_to 'Back', admin_suppliers_path %>