config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards
    resources :categories
    resources :receipts
    get "/receipts/index/:scope", to: "receipts#scoped", as: "scope"
    resources :suppliers
  end

  devise_for :users
  
  get "/welcome/chart_per_category", to: "welcome#chart_per_category"

  get 'welcome/index'
 
  root 'welcome#index'

  resources :receipts
end

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Klus-Snel.nl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="logged-in-admin">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Klus-Snel.nl Admin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Home', admin_dashboards_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Receipts', admin_receipts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Suppliers', admin_suppliers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Categories', admin_categories_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">


      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      <!-- Important to load after yield so div with chart is available -->
      <%= yield :charts_js %>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Klus-Snel.nl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="logged-in">

    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      <!-- Important to load after yield so div with chart is available -->
      <%= yield :charts_js %>

    </div>

    <%= render 'footer_menu', locals: { showPopover: !Current.project.hasReceipts } %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Klus-Snel.nl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-10 text-center">

          <%= image_tag 'logo.png' %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>